apps/analisisApp/urls.py
from django.conf.urls import url,include
#from .views import vistaPrincipal,vistaEstudiante,listaEstudiante,vistaEstudianteAdministrador,listaEstudianteAdministrador,vistaArticulo,listaArticulo,vistaComentario,listaComentario,LoginView,vistaVideo
<<<<<<< HEAD
from .views import vistaPrincipal,vistaHabitacion,listaHabitacion,vistaCliente,listaCliente,LoginView,CrearUsuarioView,EditarCliente,EditarHabitacion,vistaRegistro,listaRegistro
=======
from .views import EliminarHabitacionView,vistaPrincipal,vistaHabitacion,listaHabitacion,vistaCliente,listaCliente,LoginView,CrearUsuarioView
>>>>>>> 9341be64cd0dc4cbc49e168e200c507bd10f5d32
from django.contrib.auth.views import login,logout

urlpatterns = [
	url(r'^$', vistaPrincipal.as_view()),
	url(r'^principal$', vistaPrincipal.as_view(), name = 'principal'),
    url(r'^login$', LoginView.as_view(), name = 'login'),
    
	url(r'^habitacion$', vistaHabitacion.as_view(), name = 'habitacion'),
    url(r'^listaHabitacion$', listaHabitacion.as_view(), name = 'listaHabitacion'),
    url(r'^EliminarHabitacion/(?P<pk>\d+)/$', EliminarHabitacionView.as_view(), name = 'EliminarHabitacion'),

    

    url(r'^cliente$', vistaCliente.as_view(), name = 'cliente'),
    url(r'^listaCliente$', listaCliente.as_view(), name = 'listaCliente'),

    url(r'^accounts/logout/$', logout, name = 'logout'),

    url(r'^CrearUsuario$', CrearUsuarioView.as_view(), name = 'CrearUsuario'),


    #updates
    url(r'^EditarCliente/(?P<pk>\d+)/', EditarCliente.as_view(), name = 'EditarCliente'),
    url(r'^EditarHabitacion/(?P<pk>\d+)/', EditarHabitacion.as_view(), name = 'EditarHabitacion'),


    #registro
    url(r'^registro$', vistaRegistro.as_view(), name = 'registro'),
    url(r'^listaRegistro$', listaRegistro.as_view(), name = 'listaRegistro'),
]

parcial1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^parcial1/', include('apps.analisisApp.urls', namespace = 'analisis')),
    url(r'^admin/', admin.site.urls),
]

#propuesta y diseno de base de datos y vistas de paginas para la siguiente semana

apps/analisisApp/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class habitacion(models.Model):
	tipo_habitacion = (
		('0', 'sencillas'),
		('1', 'dobles'),
		)
	tipo = models.CharField(
		max_length= 1,
		choices = tipo_habitacion,
		default = '0',
		)
	descripcion = models.CharField(max_length = 150)
	numero = models.IntegerField()
	ocupado = models.BooleanField(default=False)
	fecha = models.DateTimeField(auto_now_add = True)
	foto = models.ImageField('Fotografia de referencia', upload_to='img/', blank=True, null=True)
	def __str__(self):
		return '%s %s %s %s' % (self.numero,self.tipo,self.ocupado,self.descripcion)

class cliente(models.Model):
	habitacion = models.ForeignKey(habitacion)
	nombre = models.CharField(max_length = 150)
	dpi = models.CharField(max_length = 20)

	def __str__(self):
		return '%s %s %s' % (self.nombre,self.dpi,self.habitacion)

class registro(models.Model):
	ccliente = models.ForeignKey(cliente)
	hhabitacion = models.ForeignKey(habitacion)
	fecha_ingreso = models.DateTimeField(auto_now_add = True)
	fecha_egreso = models.DateTimeField()

	def __str__(self):
		return '%s %s' % (self.ccliente,self.hhabitacion)

apps/analisisApp/forms.py
from django import forms
#from django import forms.ModelForm
from .models import habitacion,cliente,registro

class habitacionForm(forms.ModelForm):
	class Meta:
		model = habitacion
		fields = '__all__'

class clienteForm(forms.ModelForm):
	class Meta:
		model = cliente
		fields = '__all__'

class registroForm(forms.ModelForm):
	class meta:
		model = registro
		fields = '__all__'

apps/analisisApp/views.py
#para el logueo de los usuarios
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import login
from django.views.generic import FormView
#estas tres lineas

from django.contrib.auth.models import User


from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
<<<<<<< HEAD
from django.views.generic import TemplateView,CreateView,ListView,UpdateView
from .models import habitacion,cliente,registro
from .forms import habitacionForm,clienteForm,registroForm
=======
from django.views.generic import TemplateView,CreateView,ListView,DeleteView
from .models import habitacion,cliente
from .forms import habitacionForm,clienteForm
>>>>>>> 9341be64cd0dc4cbc49e168e200c507bd10f5d32
# Create your views here.

class vistaPrincipal(TemplateView):
	template_name = 'principal.html'

#habitacion
class vistaHabitacion(CreateView):
	template_name = 'habitacion.html'
	form_class =  habitacionForm
	success_url = reverse_lazy('analisis:principal')

class listaHabitacion(ListView):
	template_name = 'listaHabitacion.html'
	model = habitacion

	def get_queryset(self):
		return habitacion.objects.all()
#end habitacion

#cliente
class vistaCliente(CreateView):
	template_name = 'cliente.html'
	form_class =  clienteForm
	success_url = reverse_lazy('analisis:principal')

class listaCliente(ListView):
	template_name = 'listaCliente.html'
	model = cliente

	def get_queryset(self):
		return cliente.objects.all()
#end cliente

#login
class LoginView(FormView):
	template_name = 'login.html'
	form_class = AuthenticationForm
	success_url = reverse_lazy('analisis:principal')

	def form_valid(self, form):
		login(self.request, form.get_user())
		return super(LoginView, self).form_valid(form)

class vistaVideo(TemplateView):
	template_name = 'video.html'
#end logout

#create user
class CrearUsuarioView(CreateView):
	model = User
	template_name = 'CrearUsuario.html'
	form_class = UserCreationForm
	success_url = reverse_lazy('analisis:principal')
<<<<<<< HEAD
=======


class EliminarHabitacionView(DeleteView):
	template_name = 'eliminar.html'
	model = habitacion
	success_url = reverse_lazy('analisis:principal')
	
>>>>>>> 9341be64cd0dc4cbc49e168e200c507bd10f5d32
#end create user



#updates
class EditarCliente(UpdateView):
	template_name = 'cliente.html'
	model = cliente
	form_class = clienteForm
	success_url = reverse_lazy('analisis:listaCliente')

class EditarHabitacion(UpdateView):
	template_name = 'habitacion.html'
	model = habitacion
	form_class = habitacionForm
	success_url = reverse_lazy('analisis:listaHabitacion')



#registro
class vistaRegistro(CreateView):
	template_name = 'registro.html'
	form_class =  registroForm
	success_url = reverse_lazy('analisis:principal')

class listaRegistro(ListView):
	template_name = 'listaRegistro.html'
	model = registro

	def get_queryset(self):
		return registro.objects.all()



'''
usuario:	jennifer
contrasena:	aimeaime
e-mail:		jennifer@gmail.com
e-mail:		luis17velasquez@gmail.com
''' 

apps/analisisApp/templates/CrearUsuario.html
{% extends 'hereda.html' %}

{% block contenido %}
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" name="save">
	</form>

{% endblock %}

apps/analisisApp/templates/cliente.html
{% extends 'hereda.html '%}

{% block contenido %}
{% if user.is_authenticated %}
	<form method = "POST">
		{% csrf_token %}
		<table class="table table-striped table-hover">
		<tr>
			<td>Nombre: {{ form.nombre }}</td>
			<td>Dpi: {{ form.dpi }}</td>
			<!--
			<td>Dpi: {{ form.fecha_egreso }}</td>
		-->
			<td>
				<button type="submit" value="Submit" class="btn btn-success" onclick="clicked()">Agregar</button>
			</td>
		</tr>
		<tr>
			<td>
				<a href="{% url 'analisis:listaCliente' %}" class="btn btn-success">Lista de Clientes</a>
			</td>
		</tr>
		</table>
	</form>
	{% endif %}
{% endblock %}

apps/analisisApp/templates/eliminar.html
{% extends 'hereda.html' %}

{% block contenido %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea Eliminar el registro </h3>
	<button class="btn btn-danger" type="submit"> Sí, Eliminar</button>
	<A  class="btn btn-default" HREF="{% url 'analisis:principal' %}" onclick="clicked()">Cancelar</A>
<h3>
</h3>
</form>

{% endblock %}

apps/analisisApp/templates/habitacion.html
{% extends 'hereda.html '%}

{% block contenido %}
{% if user.is_authenticated %}
	<form method = "POST">
		{% csrf_token %}
		<table class="table table-striped table-hover">
		<tr>
			<td>Tipo de habitacion: {{ form.tipo }}</td>
			<td>Descripcion: {{ form.descripcion }}</td>
			<td>Numero de Habitacion: {{ form.numero }}</td>
			<td>Imagen de referencia: {{ form.foto }}</td>
			<td>
				<button type="submit" value="Submit" class="btn btn-success" onclick="clicked()">Agregar</button>
			</td>
		</tr>
		<tr>
			<td>
				<a href="{% url 'analisis:listaHabitacion' %}" class="btn btn-success">Lista habitaciones</a>
			</td>
		</tr>
		</table>
	</form>
	{% endif %}
{% endblock %}

apps/analisisApp/templates/hereda.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>pagina principal : {{ user.username }} </title>
	<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}">
	<meta charset="utf-8" name="viewport" content="width=device.width,initial-scale=1">

	<link rel="shortcut icon" href="{% static 'img/img.png' %}">

	<center>
		<h1><p>Bienvenido</p></h1>
		<h3><p>Turicentro Wuq Laq</p></h3>
	</center>

	<center>
		<img src="{% static 'img/portada2.jpg' %}">
	</center>
	
	<script type="text/javascript" src="{% static 'js/functions.js' %}"></script>

	{% if user.is_authenticated %}
		<center>
			<h3>Active user: {{ user.username }}</h3>
			<form method = "POST">
				{% csrf_token %}
				<a href="{% url 'analisis:logout' %}" class="btn btn-warning">cerrar sesion</a>
				
			</form>
		</center>
	{% endif %}

</head>
<!--
<body>
-->
<body style="background-color:powderblue;">
	<br>
	<br>
	<br>
	<br>
	<center>
	<table>
	<tr>
		<td><a href="{% url 'analisis:principal' %}" class="btn btn-default">Pagina principal</a></td>
		<td><a href="{% url 'analisis:CrearUsuario' %}" class="btn btn-success">Crear usuario</a></td>
		{% if user.is_authenticated == True %}
		<!--
		<td><a href = "http://localhost:8000/admin/login/?next=/admin/" class="btn btn-primary">Administrador DJango</a></td>
		-->
		<td><a href="{% url 'analisis:habitacion' %}" class="btn btn-success">Habitacion</a></td>
		<td><a href="{% url 'analisis:cliente' %}" class="btn btn-info">Cliente</a></td>

		<td><a href="{% url 'analisis:registro' %}" class="btn btn-default">Registros</a></td>
		{% endif %}

		{% if user.is_authenticated == False %}
			<td><a href="{% url 'analisis:login' %}" class="btn btn-default">login</a></td>
		{% endif %}

	</tr>
	</table> 
	</center>
	<br>
	<br>
	<br>
	{% block contenido %} {% endblock %}
</body>
</html>

apps/analisisApp/templates/listaCliente.html
{% extends 'hereda.html' %}

{% block contenido%}
{% if user.is_authenticated %}
<h3>Registro de clientes</h3>

<table class="table table-striped table-hover">
	<tr>
		<td>Nombre</td>
		<td>DPI</td>
		<td>fecha ingreso</td>
		<td>fecha egreso</td>
		<td>habitacion ocupada</td>
		<td>Editar cliente</td>
	</tr>

	{% for est in object_list %}
	<tr>
		<td>{{ est.nombre }}</td>
		<td>{{ est.dpi }}</td>
		<td>{{ est.fecha_ingreso }}</td>
		<td>{{ est.fecha_egreso }}</td>
		<td>{{ est.habitacion }}</td>
		<td>
			<a href="{% url 'analisis:EditarCliente' est.id %}">Editar</a>
		</td>
	</tr>
	{% endfor %}
{% endif %}
</table>

{% endblock %}

apps/analisisApp/templates/listaHabitacion.html
{% extends 'hereda.html' %}

{% block contenido%}
{% if user.is_authenticated %}
<h3>Listado de estudiantes administradores inscritos</h3>

<table class="table table-striped table-hover">
	<tr>
		<td>Numero de habitacion</td>
		<td>Tipo habitacion</td>
		<td>Descripcion</td>
		<td>Ocupado</td>
		<td>Fecha de creacion/registro habitacion</td>
		<td>Editar</td>
	</tr>

	{% for est in object_list %}
	<tr>
		<td>{{ est.numero }}</td>
		<td>{{ est.tipo }}</td>
		<td>{{ est.descripcion }}</td>
		<td>{{ est.ocupado }}</td>
		<td>{{ est.fecha }}</td>
		<td>
			<a href="{% url 'analisis:EditarHabitacion' est.id %}">Editar</a>
		</td>
		<!--
		<img src="">
<<<<<<< HEAD
		-->
=======
		<td><a href="{% url 'analisis:EliminarHabitacion' est.id %}">Eliminar</a>
>>>>>>> 9341be64cd0dc4cbc49e168e200c507bd10f5d32
	</tr>

	{% endfor %}
{% endif %}
</table>

{% endblock %}

apps/analisisApp/templates/listaRegistro.html
{% extends 'hereda.html' %}

{% block contenido%}
{% if user.is_authenticated %}
<h3>Registro de los clientes que se hospedaron en el hotel</h3>

<table class="table table-striped table-hover">
	<tr>
		<td>Cliente</td>
		<td>Habitacion</td>
		<td>fecha</td>
	</tr>

	{% for est in object_list %}
	<tr>
		<td>{{ est.ccliente }}</td>
		<td>{{ est.hhabitacion }}</td>
		<td>{{ est.fecha_ingreso }}</td>
		<td>
			<a href="{% url 'analisis:listaRegistro' est.id %}">Lista de Registros</a>
		</td>
	</tr>
	{% endfor %}
{% endif %}
</table>

{% endblock %}

apps/analisisApp/templates/login.html
{% extends 'hereda.html '%}

{% block contenido %}
<!--
<center>
	<h4>Usuario</h4>
	<input type="text" name="user">
	<h4>Contrasena</h4>
	<input type="text" name="password">
	<br>
	<br>
	<button type="submit" value="Submit" class="btn btn-success" onclick="clicked()">Agregar</button>
	<br>
	<br>
</center>
-->
<form method = "POST">
	{% csrf_token %}
	<center>
		<div class="row">
			<div class="form-group">
				<label>Usuario</label>
				{{ form.username }}
			</div>
		</div>
		<div class="row">
			<div class="form-group">
				<label>Contrasena</label>
				{{ form.password }}
			</div>
		</div>
		<button type="submit" value="Submit" class="btn btn-success">Acceder</button>
	</center>
</form>
<br>
<br>
{% endblock %}

apps/analisisApp/templates/principal.html
 {% extends 'hereda.html' %}

{% block contenido %}
<p>
<center>
	<h1>Centro turistico Wuq Laq</h1>
</center>
<h3>Les ofrece los siguientes servicios:</h3>
<br>
</p>

<p>
Ubicada en el Caserío Siete Platos, de la Aldea El Salitre, del Municipio de San Miguel Ixtlahuacán San Marcos.

Tiempo aproximado para llegar al lugar, son 20 a 30 minutos en vehículo
Laboran todos los días de la semana de 9.00 AM a 9.00 PM	
</p>

<p>
	<h4>Los servicios que ofrecen son los siguientes:</h4>
<ul>
	<li>1.	Piscinas (adultos y niños)</li>
	<li>2.	Jaccuzy para adultos y niños</li>
	<li>3.	Servicios de alimentación (Restaurant)</li>
	<li>4.	Juegos recreativos y mecánicos para niños </li>
	<li>5.	Venta de artículos de consumo diario (Tienda de abarrotes)</li>
	<li>6.	Juegos de futíos</li>
	<li>7.	Juegos de tenis de mesa</li>
	<li>8.	Juego de hockey de mesa</li>
	<li>9.	Partidos en cancha sintética</li>
	<li>10.	Servicio de gimnasio</li>
	<li>11.	Servicio de hotel (hospedaje)</li>
</ul>
</p>

<footer>Aca puedes revisar la informacion sobre el centro y mantenerte al tanto sobre nuestros servicios</footer>

{% endblock %}

apps/analisisApp/templates/registro.html
{% extends 'hereda.html '%}

{% block contenido %}
{% if user.is_authenticated %}
	<form method = "POST">
		{% csrf_token %}
		<table class="table table-striped table-hover">
		<tr>
			<td>cliente: {{ form.ccliente }}</td>
			<td>habitacion: {{ form.hhabitacion }}</td>
			<td>
				<button type="submit" value="Submit" class="btn btn-success">Agregar</button>
			</td>
		</tr>
		<tr>
			<td>
				<a href="{% url 'analisis:listaRegistro' %}" class="btn btn-success">Lista de registros</a>
			</td>
		</tr>
		</table>
	</form>
	{% endif %}
{% endblock %}